name: Build .NET Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.1

      - name: Build solution
        run: msbuild /backend/api_backend/api.sln /p:Configuration=Release